include:
  - project: graphaware/devops/gitlab-ci-templates
    file: neo4j-framework-template.yml

variables:
  JAR_NAME: uuid

stages:
  - install
  - test
  - deploy
  - postDeploy
  - trigger

delay30mins:
  extends: .delay30mins
  only:
    refs:
      - master
    variables:
      - $PARENT_VERSION

trigger:
  stage: trigger
  trigger:
    project: GraphAware/neo4j-plugins/neo4j-to-elasticsearch
    strategy: depend
  variables:
    PARENT_VERSION: $PARENT_VERSION
  only:
    refs:
      - master
    variables:
      - $PARENT_VERSION =~ /.*\..*/